/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDSrcvNqebWXkbkdYokmASvA",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-62812308",
            securityGroupIds: [
                "sg-032ee3b70b73cada8"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-272da74d",
                    availabilityZone: "eu-central-1a"
                },
                {
                    subnetId: "subnet-4082550c",
                    availabilityZone: "eu-central-1c"
                },
                {
                    subnetId: "subnet-ae8444d2",
                    availabilityZone: "eu-central-1b"
                }
            ]
        }
    }
}).schema({
    "orders_ca_short": a.model({
        index: a.integer().required(),
        amazon_order_id: a.string(),
        merchant_order_id: a.string(),
        purchase_date: a.string(),
        last_updated_date: a.string(),
        sku: a.string(),
        asin: a.string(),
        order_status: a.string(),
        item_status: a.string(),
        quantity: a.integer(),
        fulfillment_channel: a.string(),
        sales_channel: a.string(),
        order_channel: a.string(),
        ship_service_level: a.string(),
        currency: a.string(),
        item_price: a.float(),
        item_tax: a.float(),
        shipping_price: a.float(),
        shipping_tax: a.float(),
        gift_wrap_price: a.float(),
        gift_wrap_tax: a.float(),
        item_promotion_discount: a.float(),
        ship_promotion_discount: a.float(),
        promotion_ids: a.string(),
        is_business_order: a.boolean(),
        purchase_order_number: a.string(),
        price_designation: a.string(),
        partition_0: a.string(),
        partition_1: a.string()
    }).identifier([
        "index"
    ]),
    "reviews_data_ca": a.model({
        index: a.integer().required(),
        amazon_order_id: a.string(),
        merchant_order_id: a.string(),
        purchase_date: a.string(),
        sku: a.string(),
        asin: a.string(),
        quantity: a.integer(),
        review_text: a.string(),
        review_stars: a.integer()
    }).identifier([
        "index"
    ])
});
